// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI279Wxy2Mqg5ATwwyecL0thaWhmgN_J0',
    appId: '1:1026177402408:web:9d97615c5b2e69ef65971d',
    messagingSenderId: '1026177402408',
    projectId: 'gymscan-pro-v1',
    authDomain: 'gymscan-pro-v1.firebaseapp.com',
    storageBucket: 'gymscan-pro-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1KWQ0z6bdwuID0rp96LBxy4W6VHDyVY',
    appId: '1:1026177402408:android:f57b57ceae9e4fbb65971d',
    messagingSenderId: '1026177402408',
    projectId: 'gymscan-pro-v1',
    storageBucket: 'gymscan-pro-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtB-ebkGOMEl3g1xle1yrJq7tfxiPOKd0',
    appId: '1:1026177402408:ios:6b517621a428c02265971d',
    messagingSenderId: '1026177402408',
    projectId: 'gymscan-pro-v1',
    storageBucket: 'gymscan-pro-v1.firebasestorage.app',
    iosBundleId: 'com.panthers.crossfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtB-ebkGOMEl3g1xle1yrJq7tfxiPOKd0',
    appId: '1:1026177402408:ios:6b517621a428c02265971d',
    messagingSenderId: '1026177402408',
    projectId: 'gymscan-pro-v1',
    storageBucket: 'gymscan-pro-v1.firebasestorage.app',
    iosBundleId: 'com.panthers.crossfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI279Wxy2Mqg5ATwwyecL0thaWhmgN_J0',
    appId: '1:1026177402408:web:6b0d4bb2b047f93765971d',
    messagingSenderId: '1026177402408',
    projectId: 'gymscan-pro-v1',
    authDomain: 'gymscan-pro-v1.firebaseapp.com',
    storageBucket: 'gymscan-pro-v1.firebasestorage.app',
  );
}
